// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "load_feature.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic load_feature::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic load_feature::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> load_feature::ap_ST_fsm_state1 = "1";
const sc_lv<3> load_feature::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> load_feature::ap_ST_fsm_state12 = "100";
const bool load_feature::ap_const_boolean_1 = true;
const sc_lv<32> load_feature::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> load_feature::ap_const_lv1_0 = "0";
const sc_lv<3> load_feature::ap_const_lv3_0 = "000";
const sc_lv<2> load_feature::ap_const_lv2_0 = "00";
const sc_lv<4> load_feature::ap_const_lv4_0 = "0000";
const sc_lv<32> load_feature::ap_const_lv32_1 = "1";
const bool load_feature::ap_const_boolean_0 = false;
const sc_lv<1> load_feature::ap_const_lv1_1 = "1";
const sc_lv<96> load_feature::ap_const_lv96_0 = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<31> load_feature::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<64> load_feature::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> load_feature::ap_const_lv32_1F = "11111";
const sc_lv<96> load_feature::ap_const_lv96_1 = "1";
const sc_lv<31> load_feature::ap_const_lv31_1 = "1";
const sc_lv<64> load_feature::ap_const_lv64_1 = "1";
const sc_lv<32> load_feature::ap_const_lv32_2 = "10";

load_feature::load_feature(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( m_axi_feature_in_RVALID );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( or_cond4_reg_903_pp0_iter7_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( m_axi_feature_in_RVALID );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( or_cond4_reg_903_pp0_iter7_reg );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( m_axi_feature_in_RVALID );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( or_cond4_reg_903_pp0_iter7_reg );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter8);
    sensitive << ( m_axi_feature_in_RVALID );
    sensitive << ( or_cond4_reg_903_pp0_iter7_reg );

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_io);
    sensitive << ( or_cond4_reg_903 );
    sensitive << ( ap_sig_ioackin_m_axi_feature_in_ARREADY );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter7);

    SC_METHOD(thread_ap_condition_733);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond4_reg_903 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond_flatten2_fu_464_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter9 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_feature_in_ARREADY);
    sensitive << ( m_axi_feature_in_ARREADY );
    sensitive << ( ap_reg_ioackin_m_axi_feature_in_ARREADY );

    SC_METHOD(thread_bound4_fu_370_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( bound4_fu_370_p00 );

    SC_METHOD(thread_bound4_fu_370_p00);
    sensitive << ( chin );

    SC_METHOD(thread_bound4_fu_370_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( bound4_fu_370_p10 );

    SC_METHOD(thread_bound4_fu_370_p10);
    sensitive << ( bound_fu_356_p2 );

    SC_METHOD(thread_bound4_fu_370_p2);
    sensitive << ( bound4_fu_370_p0 );
    sensitive << ( bound4_fu_370_p1 );

    SC_METHOD(thread_bound_fu_356_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( bound_fu_356_p00 );

    SC_METHOD(thread_bound_fu_356_p00);
    sensitive << ( ky );

    SC_METHOD(thread_bound_fu_356_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( bound_fu_356_p10 );

    SC_METHOD(thread_bound_fu_356_p10);
    sensitive << ( kx );

    SC_METHOD(thread_bound_fu_356_p2);
    sensitive << ( bound_fu_356_p0 );
    sensitive << ( bound_fu_356_p1 );

    SC_METHOD(thread_c_mid2_fu_575_p3);
    sensitive << ( c_reg_200 );
    sensitive << ( c_s_fu_475_p2 );
    sensitive << ( exitcond_flatten_fu_490_p2 );

    SC_METHOD(thread_c_s_fu_475_p2);
    sensitive << ( c_reg_200 );

    SC_METHOD(thread_exitcond_flatten2_fu_464_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten2_reg_178 );
    sensitive << ( bound4_reg_853 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_flatten_fu_490_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_reg_211 );
    sensitive << ( bound_reg_848 );
    sensitive << ( exitcond_flatten2_fu_464_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_feature_buffer_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond4_reg_903_pp0_iter8_reg );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( tmp_29_fu_794_p1 );
    sensitive << ( tmp_28_fu_798_p1 );

    SC_METHOD(thread_feature_buffer_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_cond4_reg_903_pp0_iter8_reg );
    sensitive << ( ap_enable_reg_pp0_iter9 );

    SC_METHOD(thread_feature_buffer_d0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond4_reg_903_pp0_iter8_reg );
    sensitive << ( feature_in_addr_read_reg_928 );
    sensitive << ( ap_enable_reg_pp0_iter9 );

    SC_METHOD(thread_feature_buffer_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_cond4_reg_903_pp0_iter8_reg );
    sensitive << ( ap_enable_reg_pp0_iter9 );

    SC_METHOD(thread_feature_in_blk_n_AR);
    sensitive << ( m_axi_feature_in_ARREADY );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond4_reg_903 );

    SC_METHOD(thread_feature_in_blk_n_R);
    sensitive << ( m_axi_feature_in_RVALID );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( or_cond4_reg_903_pp0_iter7_reg );

    SC_METHOD(thread_i_2_fu_583_p2);
    sensitive << ( i_mid_fu_503_p3 );

    SC_METHOD(thread_i_cast_fu_594_p1);
    sensitive << ( i_2_fu_583_p2 );

    SC_METHOD(thread_i_cast_mid1_fu_415_p1);
    sensitive << ( i_reg_233 );

    SC_METHOD(thread_i_mid2_fu_683_p3);
    sensitive << ( i_mid_fu_503_p3 );
    sensitive << ( i_2_fu_583_p2 );
    sensitive << ( tmp_27_mid_fu_560_p3 );

    SC_METHOD(thread_i_mid_fu_503_p3);
    sensitive << ( i_reg_233 );
    sensitive << ( exitcond_flatten_fu_490_p2 );

    SC_METHOD(thread_index_1_mid2_fu_675_p3);
    sensitive << ( index_1_mid_fu_495_p3 );
    sensitive << ( tmp_27_mid_fu_560_p3 );
    sensitive << ( tmp_24_dup_fu_589_p2 );

    SC_METHOD(thread_index_1_mid_fu_495_p3);
    sensitive << ( index_1_reg_222 );
    sensitive << ( exitcond_flatten_fu_490_p2 );
    sensitive << ( index_s_fu_485_p2 );

    SC_METHOD(thread_index_2_mid2_fu_598_p3);
    sensitive << ( tmp_27_mid_fu_560_p3 );
    sensitive << ( index_2_mid_fu_511_p3 );
    sensitive << ( tmp_24_dup_fu_589_p2 );

    SC_METHOD(thread_index_2_mid_fu_511_p3);
    sensitive << ( index_2_reg_244 );
    sensitive << ( exitcond_flatten_fu_490_p2 );
    sensitive << ( index_s_fu_485_p2 );

    SC_METHOD(thread_index_mid2_fu_567_p3);
    sensitive << ( index_reg_189 );
    sensitive << ( exitcond_flatten_fu_490_p2 );
    sensitive << ( index_s_fu_485_p2 );

    SC_METHOD(thread_index_s_fu_485_p2);
    sensitive << ( index_reg_189 );
    sensitive << ( tmp_14_reg_831 );

    SC_METHOD(thread_indvar_flatten_next2_fu_469_p2);
    sensitive << ( indvar_flatten2_reg_178 );

    SC_METHOD(thread_indvar_flatten_next_fu_786_p3);
    sensitive << ( exitcond_flatten_fu_490_p2 );
    sensitive << ( indvar_flatten_op_fu_780_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_780_p2);
    sensitive << ( indvar_flatten_reg_211 );

    SC_METHOD(thread_j_2_fu_772_p3);
    sensitive << ( tmp_27_mid_fu_560_p3 );
    sensitive << ( j_mid211_op_fu_764_p3 );

    SC_METHOD(thread_j_cast_fu_455_p1);
    sensitive << ( j_reg_255 );

    SC_METHOD(thread_j_cast_mid2_cast_fu_671_p1);
    sensitive << ( j_cast_mid2_fu_663_p3 );

    SC_METHOD(thread_j_cast_mid2_fu_663_p3);
    sensitive << ( tmp_27_mid_fu_560_p3 );
    sensitive << ( j_cast_mid_fu_552_p3 );

    SC_METHOD(thread_j_cast_mid_fu_552_p3);
    sensitive << ( j_reg_255 );
    sensitive << ( exitcond_flatten_fu_490_p2 );

    SC_METHOD(thread_j_mid211_op_fu_764_p3);
    sensitive << ( exitcond_flatten_fu_490_p2 );
    sensitive << ( j_op_fu_758_p2 );

    SC_METHOD(thread_j_op_fu_758_p2);
    sensitive << ( j_reg_255 );

    SC_METHOD(thread_m_axi_feature_in_ARADDR);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond4_reg_903 );
    sensitive << ( feature_in_addr_reg_907 );
    sensitive << ( ap_reg_ioackin_m_axi_feature_in_ARREADY );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_m_axi_feature_in_ARBURST);

    SC_METHOD(thread_m_axi_feature_in_ARCACHE);

    SC_METHOD(thread_m_axi_feature_in_ARID);

    SC_METHOD(thread_m_axi_feature_in_ARLEN);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond4_reg_903 );
    sensitive << ( ap_reg_ioackin_m_axi_feature_in_ARREADY );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_m_axi_feature_in_ARLOCK);

    SC_METHOD(thread_m_axi_feature_in_ARPROT);

    SC_METHOD(thread_m_axi_feature_in_ARQOS);

    SC_METHOD(thread_m_axi_feature_in_ARREGION);

    SC_METHOD(thread_m_axi_feature_in_ARSIZE);

    SC_METHOD(thread_m_axi_feature_in_ARUSER);

    SC_METHOD(thread_m_axi_feature_in_ARVALID);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond4_reg_903 );
    sensitive << ( ap_reg_ioackin_m_axi_feature_in_ARREADY );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_m_axi_feature_in_AWADDR);

    SC_METHOD(thread_m_axi_feature_in_AWBURST);

    SC_METHOD(thread_m_axi_feature_in_AWCACHE);

    SC_METHOD(thread_m_axi_feature_in_AWID);

    SC_METHOD(thread_m_axi_feature_in_AWLEN);

    SC_METHOD(thread_m_axi_feature_in_AWLOCK);

    SC_METHOD(thread_m_axi_feature_in_AWPROT);

    SC_METHOD(thread_m_axi_feature_in_AWQOS);

    SC_METHOD(thread_m_axi_feature_in_AWREGION);

    SC_METHOD(thread_m_axi_feature_in_AWSIZE);

    SC_METHOD(thread_m_axi_feature_in_AWUSER);

    SC_METHOD(thread_m_axi_feature_in_AWVALID);

    SC_METHOD(thread_m_axi_feature_in_BREADY);

    SC_METHOD(thread_m_axi_feature_in_RREADY);
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( or_cond4_reg_903_pp0_iter7_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_m_axi_feature_in_WDATA);

    SC_METHOD(thread_m_axi_feature_in_WID);

    SC_METHOD(thread_m_axi_feature_in_WLAST);

    SC_METHOD(thread_m_axi_feature_in_WSTRB);

    SC_METHOD(thread_m_axi_feature_in_WUSER);

    SC_METHOD(thread_m_axi_feature_in_WVALID);

    SC_METHOD(thread_or_cond4_fu_721_p2);
    sensitive << ( tmp2_mid2_fu_655_p3 );
    sensitive << ( tmp1_fu_715_p2 );

    SC_METHOD(thread_rev1_fu_432_p2);
    sensitive << ( tmp_31_fu_424_p3 );

    SC_METHOD(thread_rev2_fu_619_p2);
    sensitive << ( tmp_32_fu_611_p3 );

    SC_METHOD(thread_rev3_fu_704_p2);
    sensitive << ( tmp_33_fu_696_p3 );

    SC_METHOD(thread_rev_fu_384_p2);
    sensitive << ( tmp_27_fu_376_p3 );

    SC_METHOD(thread_sext_cast_fu_402_p1);
    sensitive << ( feature_in_offset );

    SC_METHOD(thread_smax1_fu_306_p3);
    sensitive << ( tmp_13_fu_296_p2 );
    sensitive << ( tmp_24_fu_302_p1 );

    SC_METHOD(thread_smax_cast_fu_292_p1);
    sensitive << ( smax_fu_284_p3 );

    SC_METHOD(thread_smax_fu_284_p3);
    sensitive << ( tmp_s_fu_274_p2 );
    sensitive << ( tmp_20_fu_280_p1 );

    SC_METHOD(thread_sum_cast_fu_742_p1);
    sensitive << ( sum_fu_737_p2 );

    SC_METHOD(thread_sum_fu_737_p2);
    sensitive << ( sext_cast_reg_863 );
    sensitive << ( tmp_27_cast_fu_733_p1 );

    SC_METHOD(thread_tmp1_fu_715_p2);
    sensitive << ( tmp_25_fu_710_p2 );
    sensitive << ( rev3_fu_704_p2 );

    SC_METHOD(thread_tmp2_fu_449_p2);
    sensitive << ( tmp_21_fu_438_p2 );
    sensitive << ( rev1_fu_432_p2 );

    SC_METHOD(thread_tmp2_mid1_fu_649_p2);
    sensitive << ( tmp_26_mid1_fu_625_p2 );
    sensitive << ( rev2_fu_619_p2 );

    SC_METHOD(thread_tmp2_mid2_fu_655_p3);
    sensitive << ( tmp_27_mid_fu_560_p3 );
    sensitive << ( tmp2_mid3_fu_545_p3 );
    sensitive << ( tmp2_mid1_fu_649_p2 );

    SC_METHOD(thread_tmp2_mid3_fu_545_p3);
    sensitive << ( tmp2_mid_reg_858 );
    sensitive << ( exitcond_flatten_fu_490_p2 );
    sensitive << ( tmp2_fu_449_p2 );

    SC_METHOD(thread_tmp2_mid_fu_396_p2);
    sensitive << ( tmp_26_mid_fu_390_p2 );
    sensitive << ( rev_fu_384_p2 );

    SC_METHOD(thread_tmp5_mid227_v_fu_537_p3);
    sensitive << ( exitcond_flatten_fu_490_p2 );
    sensitive << ( tmp_mid_fu_532_p2 );
    sensitive << ( tmp_fu_443_p2 );

    SC_METHOD(thread_tmp5_mid2_fu_644_p1);
    sensitive << ( win );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp5_mid2_fu_644_p2);
    sensitive << ( tmp5_mid2_v_fu_636_p3 );
    sensitive << ( tmp5_mid2_fu_644_p1 );

    SC_METHOD(thread_tmp5_mid2_v_fu_636_p3);
    sensitive << ( tmp_27_mid_fu_560_p3 );
    sensitive << ( tmp5_mid227_v_fu_537_p3 );
    sensitive << ( tmp_mid1_fu_630_p2 );

    SC_METHOD(thread_tmp_13_fu_296_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ky );

    SC_METHOD(thread_tmp_14_fu_318_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_14_fu_318_p00 );

    SC_METHOD(thread_tmp_14_fu_318_p00);
    sensitive << ( smax_fu_284_p3 );

    SC_METHOD(thread_tmp_14_fu_318_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_14_fu_318_p10 );

    SC_METHOD(thread_tmp_14_fu_318_p10);
    sensitive << ( smax1_fu_306_p3 );

    SC_METHOD(thread_tmp_14_fu_318_p2);
    sensitive << ( tmp_14_fu_318_p0 );
    sensitive << ( tmp_14_fu_318_p1 );

    SC_METHOD(thread_tmp_15_fu_324_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_15_fu_324_p00 );

    SC_METHOD(thread_tmp_15_fu_324_p00);
    sensitive << ( x );

    SC_METHOD(thread_tmp_15_fu_324_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( stride );

    SC_METHOD(thread_tmp_15_fu_324_p2);
    sensitive << ( tmp_15_fu_324_p0 );
    sensitive << ( tmp_15_fu_324_p1 );

    SC_METHOD(thread_tmp_16_fu_330_p2);
    sensitive << ( padding );
    sensitive << ( tmp_15_fu_324_p2 );

    SC_METHOD(thread_tmp_17_fu_336_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_17_fu_336_p00 );

    SC_METHOD(thread_tmp_17_fu_336_p00);
    sensitive << ( y );

    SC_METHOD(thread_tmp_17_fu_336_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( stride );

    SC_METHOD(thread_tmp_17_fu_336_p2);
    sensitive << ( tmp_17_fu_336_p0 );
    sensitive << ( tmp_17_fu_336_p1 );

    SC_METHOD(thread_tmp_18_fu_342_p2);
    sensitive << ( padding );
    sensitive << ( tmp_17_fu_336_p2 );

    SC_METHOD(thread_tmp_19_fu_410_p0);
    sensitive << ( hin );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_19_fu_410_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_19_fu_410_p10 );

    SC_METHOD(thread_tmp_19_fu_410_p10);
    sensitive << ( c_reg_200 );

    SC_METHOD(thread_tmp_19_fu_410_p2);
    sensitive << ( tmp_19_fu_410_p0 );
    sensitive << ( tmp_19_fu_410_p1 );

    SC_METHOD(thread_tmp_20_fu_280_p1);
    sensitive << ( kx );

    SC_METHOD(thread_tmp_21_fu_438_p1);
    sensitive << ( hin );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_21_fu_438_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( yi_fu_419_p2 );
    sensitive << ( tmp_21_fu_438_p1 );

    SC_METHOD(thread_tmp_22_fu_459_p2);
    sensitive << ( kx );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( j_cast_fu_455_p1 );

    SC_METHOD(thread_tmp_22_mid1_fu_519_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_22_mid1_fu_519_p00 );

    SC_METHOD(thread_tmp_22_mid1_fu_519_p00);
    sensitive << ( c_s_fu_475_p2 );

    SC_METHOD(thread_tmp_22_mid1_fu_519_p1);
    sensitive << ( hin );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_22_mid1_fu_519_p2);
    sensitive << ( tmp_22_mid1_fu_519_p0 );
    sensitive << ( tmp_22_mid1_fu_519_p1 );

    SC_METHOD(thread_tmp_22_mid2_fu_524_p3);
    sensitive << ( tmp_19_fu_410_p2 );
    sensitive << ( exitcond_flatten_fu_490_p2 );
    sensitive << ( tmp_22_mid1_fu_519_p2 );

    SC_METHOD(thread_tmp_24_dup_fu_589_p2);
    sensitive << ( smax_cast_reg_826 );
    sensitive << ( index_1_mid_fu_495_p3 );

    SC_METHOD(thread_tmp_24_fu_302_p1);
    sensitive << ( ky );

    SC_METHOD(thread_tmp_25_fu_710_p1);
    sensitive << ( win );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_25_fu_710_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_flatten2_fu_464_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( xi_fu_691_p2 );
    sensitive << ( tmp_25_fu_710_p1 );

    SC_METHOD(thread_tmp_26_fu_727_p2);
    sensitive << ( xi_fu_691_p2 );
    sensitive << ( tmp5_mid2_fu_644_p2 );

    SC_METHOD(thread_tmp_26_mid1_fu_625_p1);
    sensitive << ( hin );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_26_mid1_fu_625_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_flatten2_fu_464_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( yi_mid1_fu_606_p2 );
    sensitive << ( tmp_26_mid1_fu_625_p1 );

    SC_METHOD(thread_tmp_26_mid_fu_390_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( hin );

    SC_METHOD(thread_tmp_26_mid_fu_390_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_18_fu_342_p2 );
    sensitive << ( tmp_26_mid_fu_390_p1 );

    SC_METHOD(thread_tmp_27_cast_fu_733_p1);
    sensitive << ( tmp_26_fu_727_p2 );

    SC_METHOD(thread_tmp_27_fu_376_p3);
    sensitive << ( tmp_18_fu_342_p2 );

    SC_METHOD(thread_tmp_27_mid_fu_560_p3);
    sensitive << ( tmp_s_reg_821 );
    sensitive << ( exitcond_flatten_fu_490_p2 );
    sensitive << ( tmp_22_fu_459_p2 );

    SC_METHOD(thread_tmp_28_fu_798_p1);
    sensitive << ( index_2_mid2_reg_887_pp0_iter8_reg );

    SC_METHOD(thread_tmp_29_fu_794_p1);
    sensitive << ( index_2_mid2_reg_887_pp0_iter8_reg );

    SC_METHOD(thread_tmp_30_fu_752_p2);
    sensitive << ( index_2_mid2_fu_598_p3 );

    SC_METHOD(thread_tmp_31_fu_424_p3);
    sensitive << ( yi_fu_419_p2 );

    SC_METHOD(thread_tmp_32_fu_611_p3);
    sensitive << ( yi_mid1_fu_606_p2 );

    SC_METHOD(thread_tmp_33_fu_696_p3);
    sensitive << ( xi_fu_691_p2 );

    SC_METHOD(thread_tmp_fu_443_p2);
    sensitive << ( yi_fu_419_p2 );
    sensitive << ( tmp_19_fu_410_p2 );

    SC_METHOD(thread_tmp_mid1_fu_630_p2);
    sensitive << ( yi_mid1_fu_606_p2 );
    sensitive << ( tmp_22_mid2_fu_524_p3 );

    SC_METHOD(thread_tmp_mid_fu_532_p2);
    sensitive << ( tmp_18_reg_841 );
    sensitive << ( tmp_22_mid1_fu_519_p2 );

    SC_METHOD(thread_tmp_s_fu_274_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kx );

    SC_METHOD(thread_xi_fu_691_p2);
    sensitive << ( tmp_16_reg_836 );
    sensitive << ( j_cast_mid2_cast_fu_671_p1 );

    SC_METHOD(thread_yi_fu_419_p2);
    sensitive << ( tmp_18_reg_841 );
    sensitive << ( i_cast_mid1_fu_415_p1 );

    SC_METHOD(thread_yi_mid1_fu_606_p2);
    sensitive << ( tmp_18_reg_841 );
    sensitive << ( i_cast_fu_594_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( exitcond_flatten2_fu_464_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter9 );

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_reg_ioackin_m_axi_feature_in_ARREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "load_feature_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, m_axi_feature_in_AWVALID, "(port)m_axi_feature_in_AWVALID");
    sc_trace(mVcdFile, m_axi_feature_in_AWREADY, "(port)m_axi_feature_in_AWREADY");
    sc_trace(mVcdFile, m_axi_feature_in_AWADDR, "(port)m_axi_feature_in_AWADDR");
    sc_trace(mVcdFile, m_axi_feature_in_AWID, "(port)m_axi_feature_in_AWID");
    sc_trace(mVcdFile, m_axi_feature_in_AWLEN, "(port)m_axi_feature_in_AWLEN");
    sc_trace(mVcdFile, m_axi_feature_in_AWSIZE, "(port)m_axi_feature_in_AWSIZE");
    sc_trace(mVcdFile, m_axi_feature_in_AWBURST, "(port)m_axi_feature_in_AWBURST");
    sc_trace(mVcdFile, m_axi_feature_in_AWLOCK, "(port)m_axi_feature_in_AWLOCK");
    sc_trace(mVcdFile, m_axi_feature_in_AWCACHE, "(port)m_axi_feature_in_AWCACHE");
    sc_trace(mVcdFile, m_axi_feature_in_AWPROT, "(port)m_axi_feature_in_AWPROT");
    sc_trace(mVcdFile, m_axi_feature_in_AWQOS, "(port)m_axi_feature_in_AWQOS");
    sc_trace(mVcdFile, m_axi_feature_in_AWREGION, "(port)m_axi_feature_in_AWREGION");
    sc_trace(mVcdFile, m_axi_feature_in_AWUSER, "(port)m_axi_feature_in_AWUSER");
    sc_trace(mVcdFile, m_axi_feature_in_WVALID, "(port)m_axi_feature_in_WVALID");
    sc_trace(mVcdFile, m_axi_feature_in_WREADY, "(port)m_axi_feature_in_WREADY");
    sc_trace(mVcdFile, m_axi_feature_in_WDATA, "(port)m_axi_feature_in_WDATA");
    sc_trace(mVcdFile, m_axi_feature_in_WSTRB, "(port)m_axi_feature_in_WSTRB");
    sc_trace(mVcdFile, m_axi_feature_in_WLAST, "(port)m_axi_feature_in_WLAST");
    sc_trace(mVcdFile, m_axi_feature_in_WID, "(port)m_axi_feature_in_WID");
    sc_trace(mVcdFile, m_axi_feature_in_WUSER, "(port)m_axi_feature_in_WUSER");
    sc_trace(mVcdFile, m_axi_feature_in_ARVALID, "(port)m_axi_feature_in_ARVALID");
    sc_trace(mVcdFile, m_axi_feature_in_ARREADY, "(port)m_axi_feature_in_ARREADY");
    sc_trace(mVcdFile, m_axi_feature_in_ARADDR, "(port)m_axi_feature_in_ARADDR");
    sc_trace(mVcdFile, m_axi_feature_in_ARID, "(port)m_axi_feature_in_ARID");
    sc_trace(mVcdFile, m_axi_feature_in_ARLEN, "(port)m_axi_feature_in_ARLEN");
    sc_trace(mVcdFile, m_axi_feature_in_ARSIZE, "(port)m_axi_feature_in_ARSIZE");
    sc_trace(mVcdFile, m_axi_feature_in_ARBURST, "(port)m_axi_feature_in_ARBURST");
    sc_trace(mVcdFile, m_axi_feature_in_ARLOCK, "(port)m_axi_feature_in_ARLOCK");
    sc_trace(mVcdFile, m_axi_feature_in_ARCACHE, "(port)m_axi_feature_in_ARCACHE");
    sc_trace(mVcdFile, m_axi_feature_in_ARPROT, "(port)m_axi_feature_in_ARPROT");
    sc_trace(mVcdFile, m_axi_feature_in_ARQOS, "(port)m_axi_feature_in_ARQOS");
    sc_trace(mVcdFile, m_axi_feature_in_ARREGION, "(port)m_axi_feature_in_ARREGION");
    sc_trace(mVcdFile, m_axi_feature_in_ARUSER, "(port)m_axi_feature_in_ARUSER");
    sc_trace(mVcdFile, m_axi_feature_in_RVALID, "(port)m_axi_feature_in_RVALID");
    sc_trace(mVcdFile, m_axi_feature_in_RREADY, "(port)m_axi_feature_in_RREADY");
    sc_trace(mVcdFile, m_axi_feature_in_RDATA, "(port)m_axi_feature_in_RDATA");
    sc_trace(mVcdFile, m_axi_feature_in_RLAST, "(port)m_axi_feature_in_RLAST");
    sc_trace(mVcdFile, m_axi_feature_in_RID, "(port)m_axi_feature_in_RID");
    sc_trace(mVcdFile, m_axi_feature_in_RUSER, "(port)m_axi_feature_in_RUSER");
    sc_trace(mVcdFile, m_axi_feature_in_RRESP, "(port)m_axi_feature_in_RRESP");
    sc_trace(mVcdFile, m_axi_feature_in_BVALID, "(port)m_axi_feature_in_BVALID");
    sc_trace(mVcdFile, m_axi_feature_in_BREADY, "(port)m_axi_feature_in_BREADY");
    sc_trace(mVcdFile, m_axi_feature_in_BRESP, "(port)m_axi_feature_in_BRESP");
    sc_trace(mVcdFile, m_axi_feature_in_BID, "(port)m_axi_feature_in_BID");
    sc_trace(mVcdFile, m_axi_feature_in_BUSER, "(port)m_axi_feature_in_BUSER");
    sc_trace(mVcdFile, feature_in_offset, "(port)feature_in_offset");
    sc_trace(mVcdFile, feature_buffer_address0, "(port)feature_buffer_address0");
    sc_trace(mVcdFile, feature_buffer_ce0, "(port)feature_buffer_ce0");
    sc_trace(mVcdFile, feature_buffer_we0, "(port)feature_buffer_we0");
    sc_trace(mVcdFile, feature_buffer_d0, "(port)feature_buffer_d0");
    sc_trace(mVcdFile, chin, "(port)chin");
    sc_trace(mVcdFile, kx, "(port)kx");
    sc_trace(mVcdFile, ky, "(port)ky");
    sc_trace(mVcdFile, win, "(port)win");
    sc_trace(mVcdFile, hin, "(port)hin");
    sc_trace(mVcdFile, stride, "(port)stride");
    sc_trace(mVcdFile, padding, "(port)padding");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, y, "(port)y");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, feature_in_blk_n_AR, "feature_in_blk_n_AR");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, or_cond4_reg_903, "or_cond4_reg_903");
    sc_trace(mVcdFile, feature_in_blk_n_R, "feature_in_blk_n_R");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, or_cond4_reg_903_pp0_iter7_reg, "or_cond4_reg_903_pp0_iter7_reg");
    sc_trace(mVcdFile, indvar_flatten2_reg_178, "indvar_flatten2_reg_178");
    sc_trace(mVcdFile, index_reg_189, "index_reg_189");
    sc_trace(mVcdFile, c_reg_200, "c_reg_200");
    sc_trace(mVcdFile, indvar_flatten_reg_211, "indvar_flatten_reg_211");
    sc_trace(mVcdFile, index_1_reg_222, "index_1_reg_222");
    sc_trace(mVcdFile, i_reg_233, "i_reg_233");
    sc_trace(mVcdFile, index_2_reg_244, "index_2_reg_244");
    sc_trace(mVcdFile, j_reg_255, "j_reg_255");
    sc_trace(mVcdFile, tmp_s_fu_274_p2, "tmp_s_fu_274_p2");
    sc_trace(mVcdFile, tmp_s_reg_821, "tmp_s_reg_821");
    sc_trace(mVcdFile, smax_cast_fu_292_p1, "smax_cast_fu_292_p1");
    sc_trace(mVcdFile, smax_cast_reg_826, "smax_cast_reg_826");
    sc_trace(mVcdFile, tmp_14_fu_318_p2, "tmp_14_fu_318_p2");
    sc_trace(mVcdFile, tmp_14_reg_831, "tmp_14_reg_831");
    sc_trace(mVcdFile, tmp_16_fu_330_p2, "tmp_16_fu_330_p2");
    sc_trace(mVcdFile, tmp_16_reg_836, "tmp_16_reg_836");
    sc_trace(mVcdFile, tmp_18_fu_342_p2, "tmp_18_fu_342_p2");
    sc_trace(mVcdFile, tmp_18_reg_841, "tmp_18_reg_841");
    sc_trace(mVcdFile, bound_fu_356_p2, "bound_fu_356_p2");
    sc_trace(mVcdFile, bound_reg_848, "bound_reg_848");
    sc_trace(mVcdFile, bound4_fu_370_p2, "bound4_fu_370_p2");
    sc_trace(mVcdFile, bound4_reg_853, "bound4_reg_853");
    sc_trace(mVcdFile, tmp2_mid_fu_396_p2, "tmp2_mid_fu_396_p2");
    sc_trace(mVcdFile, tmp2_mid_reg_858, "tmp2_mid_reg_858");
    sc_trace(mVcdFile, sext_cast_fu_402_p1, "sext_cast_fu_402_p1");
    sc_trace(mVcdFile, sext_cast_reg_863, "sext_cast_reg_863");
    sc_trace(mVcdFile, exitcond_flatten2_fu_464_p2, "exitcond_flatten2_fu_464_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_feature_in_ARREADY, "ap_sig_ioackin_m_axi_feature_in_ARREADY");
    sc_trace(mVcdFile, ap_block_state3_io, "ap_block_state3_io");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter6, "ap_block_state8_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter7, "ap_block_state9_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter8, "ap_block_state10_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter9, "ap_block_state11_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, indvar_flatten_next2_fu_469_p2, "indvar_flatten_next2_fu_469_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, index_mid2_fu_567_p3, "index_mid2_fu_567_p3");
    sc_trace(mVcdFile, c_mid2_fu_575_p3, "c_mid2_fu_575_p3");
    sc_trace(mVcdFile, index_2_mid2_fu_598_p3, "index_2_mid2_fu_598_p3");
    sc_trace(mVcdFile, index_2_mid2_reg_887, "index_2_mid2_reg_887");
    sc_trace(mVcdFile, index_2_mid2_reg_887_pp0_iter1_reg, "index_2_mid2_reg_887_pp0_iter1_reg");
    sc_trace(mVcdFile, index_2_mid2_reg_887_pp0_iter2_reg, "index_2_mid2_reg_887_pp0_iter2_reg");
    sc_trace(mVcdFile, index_2_mid2_reg_887_pp0_iter3_reg, "index_2_mid2_reg_887_pp0_iter3_reg");
    sc_trace(mVcdFile, index_2_mid2_reg_887_pp0_iter4_reg, "index_2_mid2_reg_887_pp0_iter4_reg");
    sc_trace(mVcdFile, index_2_mid2_reg_887_pp0_iter5_reg, "index_2_mid2_reg_887_pp0_iter5_reg");
    sc_trace(mVcdFile, index_2_mid2_reg_887_pp0_iter6_reg, "index_2_mid2_reg_887_pp0_iter6_reg");
    sc_trace(mVcdFile, index_2_mid2_reg_887_pp0_iter7_reg, "index_2_mid2_reg_887_pp0_iter7_reg");
    sc_trace(mVcdFile, index_2_mid2_reg_887_pp0_iter8_reg, "index_2_mid2_reg_887_pp0_iter8_reg");
    sc_trace(mVcdFile, index_1_mid2_fu_675_p3, "index_1_mid2_fu_675_p3");
    sc_trace(mVcdFile, i_mid2_fu_683_p3, "i_mid2_fu_683_p3");
    sc_trace(mVcdFile, or_cond4_fu_721_p2, "or_cond4_fu_721_p2");
    sc_trace(mVcdFile, or_cond4_reg_903_pp0_iter1_reg, "or_cond4_reg_903_pp0_iter1_reg");
    sc_trace(mVcdFile, or_cond4_reg_903_pp0_iter2_reg, "or_cond4_reg_903_pp0_iter2_reg");
    sc_trace(mVcdFile, or_cond4_reg_903_pp0_iter3_reg, "or_cond4_reg_903_pp0_iter3_reg");
    sc_trace(mVcdFile, or_cond4_reg_903_pp0_iter4_reg, "or_cond4_reg_903_pp0_iter4_reg");
    sc_trace(mVcdFile, or_cond4_reg_903_pp0_iter5_reg, "or_cond4_reg_903_pp0_iter5_reg");
    sc_trace(mVcdFile, or_cond4_reg_903_pp0_iter6_reg, "or_cond4_reg_903_pp0_iter6_reg");
    sc_trace(mVcdFile, or_cond4_reg_903_pp0_iter8_reg, "or_cond4_reg_903_pp0_iter8_reg");
    sc_trace(mVcdFile, feature_in_addr_reg_907, "feature_in_addr_reg_907");
    sc_trace(mVcdFile, tmp_30_fu_752_p2, "tmp_30_fu_752_p2");
    sc_trace(mVcdFile, j_2_fu_772_p3, "j_2_fu_772_p3");
    sc_trace(mVcdFile, indvar_flatten_next_fu_786_p3, "indvar_flatten_next_fu_786_p3");
    sc_trace(mVcdFile, feature_in_addr_read_reg_928, "feature_in_addr_read_reg_928");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, tmp_29_fu_794_p1, "tmp_29_fu_794_p1");
    sc_trace(mVcdFile, tmp_28_fu_798_p1, "tmp_28_fu_798_p1");
    sc_trace(mVcdFile, sum_cast_fu_742_p1, "sum_cast_fu_742_p1");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_feature_in_ARREADY, "ap_reg_ioackin_m_axi_feature_in_ARREADY");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, tmp_20_fu_280_p1, "tmp_20_fu_280_p1");
    sc_trace(mVcdFile, smax_fu_284_p3, "smax_fu_284_p3");
    sc_trace(mVcdFile, tmp_13_fu_296_p2, "tmp_13_fu_296_p2");
    sc_trace(mVcdFile, tmp_24_fu_302_p1, "tmp_24_fu_302_p1");
    sc_trace(mVcdFile, smax1_fu_306_p3, "smax1_fu_306_p3");
    sc_trace(mVcdFile, tmp_14_fu_318_p0, "tmp_14_fu_318_p0");
    sc_trace(mVcdFile, tmp_14_fu_318_p1, "tmp_14_fu_318_p1");
    sc_trace(mVcdFile, tmp_15_fu_324_p0, "tmp_15_fu_324_p0");
    sc_trace(mVcdFile, tmp_15_fu_324_p1, "tmp_15_fu_324_p1");
    sc_trace(mVcdFile, tmp_15_fu_324_p2, "tmp_15_fu_324_p2");
    sc_trace(mVcdFile, tmp_17_fu_336_p0, "tmp_17_fu_336_p0");
    sc_trace(mVcdFile, tmp_17_fu_336_p1, "tmp_17_fu_336_p1");
    sc_trace(mVcdFile, tmp_17_fu_336_p2, "tmp_17_fu_336_p2");
    sc_trace(mVcdFile, bound_fu_356_p0, "bound_fu_356_p0");
    sc_trace(mVcdFile, bound_fu_356_p1, "bound_fu_356_p1");
    sc_trace(mVcdFile, bound4_fu_370_p0, "bound4_fu_370_p0");
    sc_trace(mVcdFile, bound4_fu_370_p1, "bound4_fu_370_p1");
    sc_trace(mVcdFile, tmp_27_fu_376_p3, "tmp_27_fu_376_p3");
    sc_trace(mVcdFile, tmp_26_mid_fu_390_p1, "tmp_26_mid_fu_390_p1");
    sc_trace(mVcdFile, tmp_26_mid_fu_390_p2, "tmp_26_mid_fu_390_p2");
    sc_trace(mVcdFile, rev_fu_384_p2, "rev_fu_384_p2");
    sc_trace(mVcdFile, tmp_19_fu_410_p0, "tmp_19_fu_410_p0");
    sc_trace(mVcdFile, tmp_19_fu_410_p1, "tmp_19_fu_410_p1");
    sc_trace(mVcdFile, i_cast_mid1_fu_415_p1, "i_cast_mid1_fu_415_p1");
    sc_trace(mVcdFile, yi_fu_419_p2, "yi_fu_419_p2");
    sc_trace(mVcdFile, tmp_31_fu_424_p3, "tmp_31_fu_424_p3");
    sc_trace(mVcdFile, tmp_21_fu_438_p1, "tmp_21_fu_438_p1");
    sc_trace(mVcdFile, tmp_19_fu_410_p2, "tmp_19_fu_410_p2");
    sc_trace(mVcdFile, tmp_21_fu_438_p2, "tmp_21_fu_438_p2");
    sc_trace(mVcdFile, rev1_fu_432_p2, "rev1_fu_432_p2");
    sc_trace(mVcdFile, j_cast_fu_455_p1, "j_cast_fu_455_p1");
    sc_trace(mVcdFile, c_s_fu_475_p2, "c_s_fu_475_p2");
    sc_trace(mVcdFile, exitcond_flatten_fu_490_p2, "exitcond_flatten_fu_490_p2");
    sc_trace(mVcdFile, index_s_fu_485_p2, "index_s_fu_485_p2");
    sc_trace(mVcdFile, tmp_22_mid1_fu_519_p0, "tmp_22_mid1_fu_519_p0");
    sc_trace(mVcdFile, tmp_22_mid1_fu_519_p1, "tmp_22_mid1_fu_519_p1");
    sc_trace(mVcdFile, tmp_22_mid1_fu_519_p2, "tmp_22_mid1_fu_519_p2");
    sc_trace(mVcdFile, tmp_mid_fu_532_p2, "tmp_mid_fu_532_p2");
    sc_trace(mVcdFile, tmp_fu_443_p2, "tmp_fu_443_p2");
    sc_trace(mVcdFile, tmp2_fu_449_p2, "tmp2_fu_449_p2");
    sc_trace(mVcdFile, tmp_22_fu_459_p2, "tmp_22_fu_459_p2");
    sc_trace(mVcdFile, i_mid_fu_503_p3, "i_mid_fu_503_p3");
    sc_trace(mVcdFile, index_1_mid_fu_495_p3, "index_1_mid_fu_495_p3");
    sc_trace(mVcdFile, i_2_fu_583_p2, "i_2_fu_583_p2");
    sc_trace(mVcdFile, tmp_27_mid_fu_560_p3, "tmp_27_mid_fu_560_p3");
    sc_trace(mVcdFile, index_2_mid_fu_511_p3, "index_2_mid_fu_511_p3");
    sc_trace(mVcdFile, tmp_24_dup_fu_589_p2, "tmp_24_dup_fu_589_p2");
    sc_trace(mVcdFile, i_cast_fu_594_p1, "i_cast_fu_594_p1");
    sc_trace(mVcdFile, yi_mid1_fu_606_p2, "yi_mid1_fu_606_p2");
    sc_trace(mVcdFile, tmp_32_fu_611_p3, "tmp_32_fu_611_p3");
    sc_trace(mVcdFile, tmp_26_mid1_fu_625_p1, "tmp_26_mid1_fu_625_p1");
    sc_trace(mVcdFile, tmp_22_mid2_fu_524_p3, "tmp_22_mid2_fu_524_p3");
    sc_trace(mVcdFile, tmp5_mid227_v_fu_537_p3, "tmp5_mid227_v_fu_537_p3");
    sc_trace(mVcdFile, tmp_mid1_fu_630_p2, "tmp_mid1_fu_630_p2");
    sc_trace(mVcdFile, tmp5_mid2_v_fu_636_p3, "tmp5_mid2_v_fu_636_p3");
    sc_trace(mVcdFile, tmp5_mid2_fu_644_p1, "tmp5_mid2_fu_644_p1");
    sc_trace(mVcdFile, tmp_26_mid1_fu_625_p2, "tmp_26_mid1_fu_625_p2");
    sc_trace(mVcdFile, rev2_fu_619_p2, "rev2_fu_619_p2");
    sc_trace(mVcdFile, tmp2_mid3_fu_545_p3, "tmp2_mid3_fu_545_p3");
    sc_trace(mVcdFile, tmp2_mid1_fu_649_p2, "tmp2_mid1_fu_649_p2");
    sc_trace(mVcdFile, j_cast_mid_fu_552_p3, "j_cast_mid_fu_552_p3");
    sc_trace(mVcdFile, j_cast_mid2_fu_663_p3, "j_cast_mid2_fu_663_p3");
    sc_trace(mVcdFile, j_cast_mid2_cast_fu_671_p1, "j_cast_mid2_cast_fu_671_p1");
    sc_trace(mVcdFile, xi_fu_691_p2, "xi_fu_691_p2");
    sc_trace(mVcdFile, tmp_33_fu_696_p3, "tmp_33_fu_696_p3");
    sc_trace(mVcdFile, tmp_25_fu_710_p1, "tmp_25_fu_710_p1");
    sc_trace(mVcdFile, tmp_25_fu_710_p2, "tmp_25_fu_710_p2");
    sc_trace(mVcdFile, rev3_fu_704_p2, "rev3_fu_704_p2");
    sc_trace(mVcdFile, tmp2_mid2_fu_655_p3, "tmp2_mid2_fu_655_p3");
    sc_trace(mVcdFile, tmp1_fu_715_p2, "tmp1_fu_715_p2");
    sc_trace(mVcdFile, tmp5_mid2_fu_644_p2, "tmp5_mid2_fu_644_p2");
    sc_trace(mVcdFile, tmp_26_fu_727_p2, "tmp_26_fu_727_p2");
    sc_trace(mVcdFile, tmp_27_cast_fu_733_p1, "tmp_27_cast_fu_733_p1");
    sc_trace(mVcdFile, sum_fu_737_p2, "sum_fu_737_p2");
    sc_trace(mVcdFile, j_op_fu_758_p2, "j_op_fu_758_p2");
    sc_trace(mVcdFile, j_mid211_op_fu_764_p3, "j_mid211_op_fu_764_p3");
    sc_trace(mVcdFile, indvar_flatten_op_fu_780_p2, "indvar_flatten_op_fu_780_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, bound4_fu_370_p00, "bound4_fu_370_p00");
    sc_trace(mVcdFile, bound4_fu_370_p10, "bound4_fu_370_p10");
    sc_trace(mVcdFile, bound_fu_356_p00, "bound_fu_356_p00");
    sc_trace(mVcdFile, bound_fu_356_p10, "bound_fu_356_p10");
    sc_trace(mVcdFile, tmp_14_fu_318_p00, "tmp_14_fu_318_p00");
    sc_trace(mVcdFile, tmp_14_fu_318_p10, "tmp_14_fu_318_p10");
    sc_trace(mVcdFile, tmp_15_fu_324_p00, "tmp_15_fu_324_p00");
    sc_trace(mVcdFile, tmp_17_fu_336_p00, "tmp_17_fu_336_p00");
    sc_trace(mVcdFile, tmp_19_fu_410_p10, "tmp_19_fu_410_p10");
    sc_trace(mVcdFile, tmp_22_mid1_fu_519_p00, "tmp_22_mid1_fu_519_p00");
    sc_trace(mVcdFile, ap_condition_733, "ap_condition_733");
#endif

    }
}

load_feature::~load_feature() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void load_feature::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter9 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_feature_in_ARREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_condition_733.read(), ap_const_boolean_1)) {
            if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
                ap_reg_ioackin_m_axi_feature_in_ARREADY = ap_const_logic_0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, m_axi_feature_in_ARREADY.read()) && 
                        esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0))) {
                ap_reg_ioackin_m_axi_feature_in_ARREADY = ap_const_logic_1;
            }
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_464_p2.read()))) {
        c_reg_200 = c_mid2_fu_575_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        c_reg_200 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_464_p2.read()))) {
        i_reg_233 = i_mid2_fu_683_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_233 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_464_p2.read()))) {
        index_1_reg_222 = index_1_mid2_fu_675_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        index_1_reg_222 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_464_p2.read()))) {
        index_2_reg_244 = tmp_30_fu_752_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        index_2_reg_244 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_464_p2.read()))) {
        index_reg_189 = index_mid2_fu_567_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        index_reg_189 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_464_p2.read()))) {
        indvar_flatten2_reg_178 = indvar_flatten_next2_fu_469_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten2_reg_178 = ap_const_lv96_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_464_p2.read()))) {
        indvar_flatten_reg_211 = indvar_flatten_next_fu_786_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_211 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_464_p2.read()))) {
        j_reg_255 = j_2_fu_772_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_reg_255 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        bound4_reg_853 = bound4_fu_370_p2.read();
        bound_reg_848 = bound_fu_356_p2.read();
        sext_cast_reg_863 = sext_cast_fu_402_p1.read();
        smax_cast_reg_826 = smax_cast_fu_292_p1.read();
        tmp2_mid_reg_858 = tmp2_mid_fu_396_p2.read();
        tmp_14_reg_831 = tmp_14_fu_318_p2.read();
        tmp_16_reg_836 = tmp_16_fu_330_p2.read();
        tmp_18_reg_841 = tmp_18_fu_342_p2.read();
        tmp_s_reg_821 = tmp_s_fu_274_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_reg_903_pp0_iter7_reg.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        feature_in_addr_read_reg_928 = m_axi_feature_in_RDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_464_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_fu_721_p2.read()))) {
        feature_in_addr_reg_907 =  (sc_lv<32>) (sum_cast_fu_742_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten2_fu_464_p2.read()))) {
        index_2_mid2_reg_887 = index_2_mid2_fu_598_p3.read();
        or_cond4_reg_903 = or_cond4_fu_721_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        index_2_mid2_reg_887_pp0_iter1_reg = index_2_mid2_reg_887.read();
        or_cond4_reg_903_pp0_iter1_reg = or_cond4_reg_903.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        index_2_mid2_reg_887_pp0_iter2_reg = index_2_mid2_reg_887_pp0_iter1_reg.read();
        index_2_mid2_reg_887_pp0_iter3_reg = index_2_mid2_reg_887_pp0_iter2_reg.read();
        index_2_mid2_reg_887_pp0_iter4_reg = index_2_mid2_reg_887_pp0_iter3_reg.read();
        index_2_mid2_reg_887_pp0_iter5_reg = index_2_mid2_reg_887_pp0_iter4_reg.read();
        index_2_mid2_reg_887_pp0_iter6_reg = index_2_mid2_reg_887_pp0_iter5_reg.read();
        index_2_mid2_reg_887_pp0_iter7_reg = index_2_mid2_reg_887_pp0_iter6_reg.read();
        index_2_mid2_reg_887_pp0_iter8_reg = index_2_mid2_reg_887_pp0_iter7_reg.read();
        or_cond4_reg_903_pp0_iter2_reg = or_cond4_reg_903_pp0_iter1_reg.read();
        or_cond4_reg_903_pp0_iter3_reg = or_cond4_reg_903_pp0_iter2_reg.read();
        or_cond4_reg_903_pp0_iter4_reg = or_cond4_reg_903_pp0_iter3_reg.read();
        or_cond4_reg_903_pp0_iter5_reg = or_cond4_reg_903_pp0_iter4_reg.read();
        or_cond4_reg_903_pp0_iter6_reg = or_cond4_reg_903_pp0_iter5_reg.read();
        or_cond4_reg_903_pp0_iter7_reg = or_cond4_reg_903_pp0_iter6_reg.read();
        or_cond4_reg_903_pp0_iter8_reg = or_cond4_reg_903_pp0_iter7_reg.read();
    }
}

void load_feature::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void load_feature::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void load_feature::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[2];
}

void load_feature::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void load_feature::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_reg_903_pp0_iter7_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, m_axi_feature_in_RVALID.read()));
}

void load_feature::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_reg_903_pp0_iter7_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, m_axi_feature_in_RVALID.read())));
}

void load_feature::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_reg_903_pp0_iter7_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, m_axi_feature_in_RVALID.read())));
}

void load_feature::thread_ap_block_state10_pp0_stage0_iter8() {
    ap_block_state10_pp0_stage0_iter8 = (esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_reg_903_pp0_iter7_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, m_axi_feature_in_RVALID.read()));
}

void load_feature::thread_ap_block_state11_pp0_stage0_iter9() {
    ap_block_state11_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void load_feature::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void load_feature::thread_ap_block_state3_io() {
    ap_block_state3_io = (esl_seteq<1,1,1>(or_cond4_reg_903.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_feature_in_ARREADY.read()));
}

void load_feature::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void load_feature::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void load_feature::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void load_feature::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void load_feature::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void load_feature::thread_ap_block_state8_pp0_stage0_iter6() {
    ap_block_state8_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void load_feature::thread_ap_block_state9_pp0_stage0_iter7() {
    ap_block_state9_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void load_feature::thread_ap_condition_733() {
    ap_condition_733 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(or_cond4_reg_903.read(), ap_const_lv1_1));
}

void load_feature::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten2_fu_464_p2.read())) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void load_feature::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void load_feature::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void load_feature::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void load_feature::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void load_feature::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void load_feature::thread_ap_sig_ioackin_m_axi_feature_in_ARREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_feature_in_ARREADY.read())) {
        ap_sig_ioackin_m_axi_feature_in_ARREADY = m_axi_feature_in_ARREADY.read();
    } else {
        ap_sig_ioackin_m_axi_feature_in_ARREADY = ap_const_logic_1;
    }
}

void load_feature::thread_bound4_fu_370_p0() {
    bound4_fu_370_p0 =  (sc_lv<32>) (bound4_fu_370_p00.read());
}

void load_feature::thread_bound4_fu_370_p00() {
    bound4_fu_370_p00 = esl_zext<96,32>(chin.read());
}

void load_feature::thread_bound4_fu_370_p1() {
    bound4_fu_370_p1 =  (sc_lv<64>) (bound4_fu_370_p10.read());
}

void load_feature::thread_bound4_fu_370_p10() {
    bound4_fu_370_p10 = esl_zext<96,64>(bound_fu_356_p2.read());
}

void load_feature::thread_bound4_fu_370_p2() {
    bound4_fu_370_p2 = (!bound4_fu_370_p0.read().is_01() || !bound4_fu_370_p1.read().is_01())? sc_lv<96>(): sc_biguint<32>(bound4_fu_370_p0.read()) * sc_biguint<64>(bound4_fu_370_p1.read());
}

void load_feature::thread_bound_fu_356_p0() {
    bound_fu_356_p0 =  (sc_lv<32>) (bound_fu_356_p00.read());
}

void load_feature::thread_bound_fu_356_p00() {
    bound_fu_356_p00 = esl_zext<64,32>(ky.read());
}

void load_feature::thread_bound_fu_356_p1() {
    bound_fu_356_p1 =  (sc_lv<32>) (bound_fu_356_p10.read());
}

void load_feature::thread_bound_fu_356_p10() {
    bound_fu_356_p10 = esl_zext<64,32>(kx.read());
}

void load_feature::thread_bound_fu_356_p2() {
    bound_fu_356_p2 = (!bound_fu_356_p0.read().is_01() || !bound_fu_356_p1.read().is_01())? sc_lv<64>(): sc_biguint<32>(bound_fu_356_p0.read()) * sc_biguint<32>(bound_fu_356_p1.read());
}

void load_feature::thread_c_mid2_fu_575_p3() {
    c_mid2_fu_575_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<31>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? c_s_fu_475_p2.read(): c_reg_200.read());
}

void load_feature::thread_c_s_fu_475_p2() {
    c_s_fu_475_p2 = (!c_reg_200.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(c_reg_200.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void load_feature::thread_exitcond_flatten2_fu_464_p2() {
    exitcond_flatten2_fu_464_p2 = (!indvar_flatten2_reg_178.read().is_01() || !bound4_reg_853.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten2_reg_178.read() == bound4_reg_853.read());
}

void load_feature::thread_exitcond_flatten_fu_490_p2() {
    exitcond_flatten_fu_490_p2 = (!indvar_flatten_reg_211.read().is_01() || !bound_reg_848.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_211.read() == bound_reg_848.read());
}

void load_feature::thread_feature_buffer_address0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_reg_903_pp0_iter8_reg.read())) {
            feature_buffer_address0 =  (sc_lv<15>) (tmp_28_fu_798_p1.read());
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_reg_903_pp0_iter8_reg.read())) {
            feature_buffer_address0 =  (sc_lv<15>) (tmp_29_fu_794_p1.read());
        } else {
            feature_buffer_address0 = "XXXXXXXXXXXXXXX";
        }
    } else {
        feature_buffer_address0 = "XXXXXXXXXXXXXXX";
    }
}

void load_feature::thread_feature_buffer_ce0() {
    if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_reg_903_pp0_iter8_reg.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_reg_903_pp0_iter8_reg.read())))) {
        feature_buffer_ce0 = ap_const_logic_1;
    } else {
        feature_buffer_ce0 = ap_const_logic_0;
    }
}

void load_feature::thread_feature_buffer_d0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_reg_903_pp0_iter8_reg.read())) {
            feature_buffer_d0 = feature_in_addr_read_reg_928.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_reg_903_pp0_iter8_reg.read())) {
            feature_buffer_d0 = ap_const_lv32_0;
        } else {
            feature_buffer_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        feature_buffer_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void load_feature::thread_feature_buffer_we0() {
    if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_reg_903_pp0_iter8_reg.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_reg_903_pp0_iter8_reg.read())))) {
        feature_buffer_we0 = ap_const_logic_1;
    } else {
        feature_buffer_we0 = ap_const_logic_0;
    }
}

void load_feature::thread_feature_in_blk_n_AR() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(or_cond4_reg_903.read(), ap_const_lv1_1))) {
        feature_in_blk_n_AR = m_axi_feature_in_ARREADY.read();
    } else {
        feature_in_blk_n_AR = ap_const_logic_1;
    }
}

void load_feature::thread_feature_in_blk_n_R() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_reg_903_pp0_iter7_reg.read()))) {
        feature_in_blk_n_R = m_axi_feature_in_RVALID.read();
    } else {
        feature_in_blk_n_R = ap_const_logic_1;
    }
}

void load_feature::thread_i_2_fu_583_p2() {
    i_2_fu_583_p2 = (!i_mid_fu_503_p3.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(i_mid_fu_503_p3.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void load_feature::thread_i_cast_fu_594_p1() {
    i_cast_fu_594_p1 = esl_zext<32,31>(i_2_fu_583_p2.read());
}

void load_feature::thread_i_cast_mid1_fu_415_p1() {
    i_cast_mid1_fu_415_p1 = esl_zext<32,31>(i_reg_233.read());
}

void load_feature::thread_i_mid2_fu_683_p3() {
    i_mid2_fu_683_p3 = (!tmp_27_mid_fu_560_p3.read()[0].is_01())? sc_lv<31>(): ((tmp_27_mid_fu_560_p3.read()[0].to_bool())? i_mid_fu_503_p3.read(): i_2_fu_583_p2.read());
}

void load_feature::thread_i_mid_fu_503_p3() {
    i_mid_fu_503_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<31>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? ap_const_lv31_0: i_reg_233.read());
}

void load_feature::thread_index_1_mid2_fu_675_p3() {
    index_1_mid2_fu_675_p3 = (!tmp_27_mid_fu_560_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_27_mid_fu_560_p3.read()[0].to_bool())? index_1_mid_fu_495_p3.read(): tmp_24_dup_fu_589_p2.read());
}

void load_feature::thread_index_1_mid_fu_495_p3() {
    index_1_mid_fu_495_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<32>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? index_s_fu_485_p2.read(): index_1_reg_222.read());
}

void load_feature::thread_index_2_mid2_fu_598_p3() {
    index_2_mid2_fu_598_p3 = (!tmp_27_mid_fu_560_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_27_mid_fu_560_p3.read()[0].to_bool())? index_2_mid_fu_511_p3.read(): tmp_24_dup_fu_589_p2.read());
}

void load_feature::thread_index_2_mid_fu_511_p3() {
    index_2_mid_fu_511_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<32>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? index_s_fu_485_p2.read(): index_2_reg_244.read());
}

void load_feature::thread_index_mid2_fu_567_p3() {
    index_mid2_fu_567_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<32>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? index_s_fu_485_p2.read(): index_reg_189.read());
}

void load_feature::thread_index_s_fu_485_p2() {
    index_s_fu_485_p2 = (!tmp_14_reg_831.read().is_01() || !index_reg_189.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_14_reg_831.read()) + sc_biguint<32>(index_reg_189.read()));
}

void load_feature::thread_indvar_flatten_next2_fu_469_p2() {
    indvar_flatten_next2_fu_469_p2 = (!indvar_flatten2_reg_178.read().is_01() || !ap_const_lv96_1.is_01())? sc_lv<96>(): (sc_biguint<96>(indvar_flatten2_reg_178.read()) + sc_biguint<96>(ap_const_lv96_1));
}

void load_feature::thread_indvar_flatten_next_fu_786_p3() {
    indvar_flatten_next_fu_786_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<64>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? ap_const_lv64_1: indvar_flatten_op_fu_780_p2.read());
}

void load_feature::thread_indvar_flatten_op_fu_780_p2() {
    indvar_flatten_op_fu_780_p2 = (!indvar_flatten_reg_211.read().is_01() || !ap_const_lv64_1.is_01())? sc_lv<64>(): (sc_biguint<64>(indvar_flatten_reg_211.read()) + sc_biguint<64>(ap_const_lv64_1));
}

void load_feature::thread_j_2_fu_772_p3() {
    j_2_fu_772_p3 = (!tmp_27_mid_fu_560_p3.read()[0].is_01())? sc_lv<31>(): ((tmp_27_mid_fu_560_p3.read()[0].to_bool())? j_mid211_op_fu_764_p3.read(): ap_const_lv31_1);
}

void load_feature::thread_j_cast_fu_455_p1() {
    j_cast_fu_455_p1 = esl_zext<32,31>(j_reg_255.read());
}

void load_feature::thread_j_cast_mid2_cast_fu_671_p1() {
    j_cast_mid2_cast_fu_671_p1 = esl_zext<32,31>(j_cast_mid2_fu_663_p3.read());
}

void load_feature::thread_j_cast_mid2_fu_663_p3() {
    j_cast_mid2_fu_663_p3 = (!tmp_27_mid_fu_560_p3.read()[0].is_01())? sc_lv<31>(): ((tmp_27_mid_fu_560_p3.read()[0].to_bool())? j_cast_mid_fu_552_p3.read(): ap_const_lv31_0);
}

void load_feature::thread_j_cast_mid_fu_552_p3() {
    j_cast_mid_fu_552_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<31>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? ap_const_lv31_0: j_reg_255.read());
}

void load_feature::thread_j_mid211_op_fu_764_p3() {
    j_mid211_op_fu_764_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<31>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? ap_const_lv31_1: j_op_fu_758_p2.read());
}

void load_feature::thread_j_op_fu_758_p2() {
    j_op_fu_758_p2 = (!j_reg_255.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(j_reg_255.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void load_feature::thread_m_axi_feature_in_ARADDR() {
    m_axi_feature_in_ARADDR = feature_in_addr_reg_907.read();
}

void load_feature::thread_m_axi_feature_in_ARBURST() {
    m_axi_feature_in_ARBURST = ap_const_lv2_0;
}

void load_feature::thread_m_axi_feature_in_ARCACHE() {
    m_axi_feature_in_ARCACHE = ap_const_lv4_0;
}

void load_feature::thread_m_axi_feature_in_ARID() {
    m_axi_feature_in_ARID = ap_const_lv1_0;
}

void load_feature::thread_m_axi_feature_in_ARLEN() {
    m_axi_feature_in_ARLEN = ap_const_lv32_1;
}

void load_feature::thread_m_axi_feature_in_ARLOCK() {
    m_axi_feature_in_ARLOCK = ap_const_lv2_0;
}

void load_feature::thread_m_axi_feature_in_ARPROT() {
    m_axi_feature_in_ARPROT = ap_const_lv3_0;
}

void load_feature::thread_m_axi_feature_in_ARQOS() {
    m_axi_feature_in_ARQOS = ap_const_lv4_0;
}

void load_feature::thread_m_axi_feature_in_ARREGION() {
    m_axi_feature_in_ARREGION = ap_const_lv4_0;
}

void load_feature::thread_m_axi_feature_in_ARSIZE() {
    m_axi_feature_in_ARSIZE = ap_const_lv3_0;
}

void load_feature::thread_m_axi_feature_in_ARUSER() {
    m_axi_feature_in_ARUSER = ap_const_lv1_0;
}

void load_feature::thread_m_axi_feature_in_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(or_cond4_reg_903.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_feature_in_ARREADY.read()))) {
        m_axi_feature_in_ARVALID = ap_const_logic_1;
    } else {
        m_axi_feature_in_ARVALID = ap_const_logic_0;
    }
}

void load_feature::thread_m_axi_feature_in_AWADDR() {
    m_axi_feature_in_AWADDR = ap_const_lv32_0;
}

void load_feature::thread_m_axi_feature_in_AWBURST() {
    m_axi_feature_in_AWBURST = ap_const_lv2_0;
}

void load_feature::thread_m_axi_feature_in_AWCACHE() {
    m_axi_feature_in_AWCACHE = ap_const_lv4_0;
}

void load_feature::thread_m_axi_feature_in_AWID() {
    m_axi_feature_in_AWID = ap_const_lv1_0;
}

void load_feature::thread_m_axi_feature_in_AWLEN() {
    m_axi_feature_in_AWLEN = ap_const_lv32_0;
}

void load_feature::thread_m_axi_feature_in_AWLOCK() {
    m_axi_feature_in_AWLOCK = ap_const_lv2_0;
}

void load_feature::thread_m_axi_feature_in_AWPROT() {
    m_axi_feature_in_AWPROT = ap_const_lv3_0;
}

void load_feature::thread_m_axi_feature_in_AWQOS() {
    m_axi_feature_in_AWQOS = ap_const_lv4_0;
}

void load_feature::thread_m_axi_feature_in_AWREGION() {
    m_axi_feature_in_AWREGION = ap_const_lv4_0;
}

void load_feature::thread_m_axi_feature_in_AWSIZE() {
    m_axi_feature_in_AWSIZE = ap_const_lv3_0;
}

void load_feature::thread_m_axi_feature_in_AWUSER() {
    m_axi_feature_in_AWUSER = ap_const_lv1_0;
}

void load_feature::thread_m_axi_feature_in_AWVALID() {
    m_axi_feature_in_AWVALID = ap_const_logic_0;
}

void load_feature::thread_m_axi_feature_in_BREADY() {
    m_axi_feature_in_BREADY = ap_const_logic_0;
}

void load_feature::thread_m_axi_feature_in_RREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_cond4_reg_903_pp0_iter7_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        m_axi_feature_in_RREADY = ap_const_logic_1;
    } else {
        m_axi_feature_in_RREADY = ap_const_logic_0;
    }
}

void load_feature::thread_m_axi_feature_in_WDATA() {
    m_axi_feature_in_WDATA = ap_const_lv32_0;
}

void load_feature::thread_m_axi_feature_in_WID() {
    m_axi_feature_in_WID = ap_const_lv1_0;
}

void load_feature::thread_m_axi_feature_in_WLAST() {
    m_axi_feature_in_WLAST = ap_const_logic_0;
}

void load_feature::thread_m_axi_feature_in_WSTRB() {
    m_axi_feature_in_WSTRB = ap_const_lv4_0;
}

void load_feature::thread_m_axi_feature_in_WUSER() {
    m_axi_feature_in_WUSER = ap_const_lv1_0;
}

void load_feature::thread_m_axi_feature_in_WVALID() {
    m_axi_feature_in_WVALID = ap_const_logic_0;
}

void load_feature::thread_or_cond4_fu_721_p2() {
    or_cond4_fu_721_p2 = (tmp2_mid2_fu_655_p3.read() & tmp1_fu_715_p2.read());
}

void load_feature::thread_rev1_fu_432_p2() {
    rev1_fu_432_p2 = (tmp_31_fu_424_p3.read() ^ ap_const_lv1_1);
}

void load_feature::thread_rev2_fu_619_p2() {
    rev2_fu_619_p2 = (tmp_32_fu_611_p3.read() ^ ap_const_lv1_1);
}

void load_feature::thread_rev3_fu_704_p2() {
    rev3_fu_704_p2 = (tmp_33_fu_696_p3.read() ^ ap_const_lv1_1);
}

void load_feature::thread_rev_fu_384_p2() {
    rev_fu_384_p2 = (tmp_27_fu_376_p3.read() ^ ap_const_lv1_1);
}

void load_feature::thread_sext_cast_fu_402_p1() {
    sext_cast_fu_402_p1 = esl_zext<33,30>(feature_in_offset.read());
}

void load_feature::thread_smax1_fu_306_p3() {
    smax1_fu_306_p3 = (!tmp_13_fu_296_p2.read()[0].is_01())? sc_lv<31>(): ((tmp_13_fu_296_p2.read()[0].to_bool())? tmp_24_fu_302_p1.read(): ap_const_lv31_0);
}

void load_feature::thread_smax_cast_fu_292_p1() {
    smax_cast_fu_292_p1 = esl_zext<32,31>(smax_fu_284_p3.read());
}

void load_feature::thread_smax_fu_284_p3() {
    smax_fu_284_p3 = (!tmp_s_fu_274_p2.read()[0].is_01())? sc_lv<31>(): ((tmp_s_fu_274_p2.read()[0].to_bool())? tmp_20_fu_280_p1.read(): ap_const_lv31_0);
}

void load_feature::thread_sum_cast_fu_742_p1() {
    sum_cast_fu_742_p1 = esl_sext<64,33>(sum_fu_737_p2.read());
}

void load_feature::thread_sum_fu_737_p2() {
    sum_fu_737_p2 = (!sext_cast_reg_863.read().is_01() || !tmp_27_cast_fu_733_p1.read().is_01())? sc_lv<33>(): (sc_biguint<33>(sext_cast_reg_863.read()) + sc_bigint<33>(tmp_27_cast_fu_733_p1.read()));
}

void load_feature::thread_tmp1_fu_715_p2() {
    tmp1_fu_715_p2 = (tmp_25_fu_710_p2.read() & rev3_fu_704_p2.read());
}

void load_feature::thread_tmp2_fu_449_p2() {
    tmp2_fu_449_p2 = (tmp_21_fu_438_p2.read() & rev1_fu_432_p2.read());
}

void load_feature::thread_tmp2_mid1_fu_649_p2() {
    tmp2_mid1_fu_649_p2 = (tmp_26_mid1_fu_625_p2.read() & rev2_fu_619_p2.read());
}

void load_feature::thread_tmp2_mid2_fu_655_p3() {
    tmp2_mid2_fu_655_p3 = (!tmp_27_mid_fu_560_p3.read()[0].is_01())? sc_lv<1>(): ((tmp_27_mid_fu_560_p3.read()[0].to_bool())? tmp2_mid3_fu_545_p3.read(): tmp2_mid1_fu_649_p2.read());
}

void load_feature::thread_tmp2_mid3_fu_545_p3() {
    tmp2_mid3_fu_545_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? tmp2_mid_reg_858.read(): tmp2_fu_449_p2.read());
}

void load_feature::thread_tmp2_mid_fu_396_p2() {
    tmp2_mid_fu_396_p2 = (tmp_26_mid_fu_390_p2.read() & rev_fu_384_p2.read());
}

void load_feature::thread_tmp5_mid227_v_fu_537_p3() {
    tmp5_mid227_v_fu_537_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<32>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? tmp_mid_fu_532_p2.read(): tmp_fu_443_p2.read());
}

void load_feature::thread_tmp5_mid2_fu_644_p1() {
    tmp5_mid2_fu_644_p1 = win.read();
}

void load_feature::thread_tmp5_mid2_fu_644_p2() {
    tmp5_mid2_fu_644_p2 = (!tmp5_mid2_v_fu_636_p3.read().is_01() || !tmp5_mid2_fu_644_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(tmp5_mid2_v_fu_636_p3.read()) * sc_bigint<32>(tmp5_mid2_fu_644_p1.read());
}

void load_feature::thread_tmp5_mid2_v_fu_636_p3() {
    tmp5_mid2_v_fu_636_p3 = (!tmp_27_mid_fu_560_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_27_mid_fu_560_p3.read()[0].to_bool())? tmp5_mid227_v_fu_537_p3.read(): tmp_mid1_fu_630_p2.read());
}

void load_feature::thread_tmp_13_fu_296_p2() {
    tmp_13_fu_296_p2 = (!ky.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(ky.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void load_feature::thread_tmp_14_fu_318_p0() {
    tmp_14_fu_318_p0 =  (sc_lv<31>) (tmp_14_fu_318_p00.read());
}

void load_feature::thread_tmp_14_fu_318_p00() {
    tmp_14_fu_318_p00 = esl_zext<32,31>(smax_fu_284_p3.read());
}

void load_feature::thread_tmp_14_fu_318_p1() {
    tmp_14_fu_318_p1 =  (sc_lv<31>) (tmp_14_fu_318_p10.read());
}

void load_feature::thread_tmp_14_fu_318_p10() {
    tmp_14_fu_318_p10 = esl_zext<32,31>(smax1_fu_306_p3.read());
}

void load_feature::thread_tmp_14_fu_318_p2() {
    tmp_14_fu_318_p2 = (!tmp_14_fu_318_p0.read().is_01() || !tmp_14_fu_318_p1.read().is_01())? sc_lv<32>(): sc_biguint<31>(tmp_14_fu_318_p0.read()) * sc_biguint<31>(tmp_14_fu_318_p1.read());
}

void load_feature::thread_tmp_15_fu_324_p0() {
    tmp_15_fu_324_p0 =  (sc_lv<31>) (tmp_15_fu_324_p00.read());
}

void load_feature::thread_tmp_15_fu_324_p00() {
    tmp_15_fu_324_p00 = esl_zext<32,31>(x.read());
}

void load_feature::thread_tmp_15_fu_324_p1() {
    tmp_15_fu_324_p1 = stride.read();
}

void load_feature::thread_tmp_15_fu_324_p2() {
    tmp_15_fu_324_p2 = (!tmp_15_fu_324_p0.read().is_01() || !tmp_15_fu_324_p1.read().is_01())? sc_lv<32>(): sc_biguint<31>(tmp_15_fu_324_p0.read()) * sc_bigint<32>(tmp_15_fu_324_p1.read());
}

void load_feature::thread_tmp_16_fu_330_p2() {
    tmp_16_fu_330_p2 = (!tmp_15_fu_324_p2.read().is_01() || !padding.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_15_fu_324_p2.read()) - sc_biguint<32>(padding.read()));
}

void load_feature::thread_tmp_17_fu_336_p0() {
    tmp_17_fu_336_p0 =  (sc_lv<31>) (tmp_17_fu_336_p00.read());
}

void load_feature::thread_tmp_17_fu_336_p00() {
    tmp_17_fu_336_p00 = esl_zext<32,31>(y.read());
}

void load_feature::thread_tmp_17_fu_336_p1() {
    tmp_17_fu_336_p1 = stride.read();
}

void load_feature::thread_tmp_17_fu_336_p2() {
    tmp_17_fu_336_p2 = (!tmp_17_fu_336_p0.read().is_01() || !tmp_17_fu_336_p1.read().is_01())? sc_lv<32>(): sc_biguint<31>(tmp_17_fu_336_p0.read()) * sc_bigint<32>(tmp_17_fu_336_p1.read());
}

void load_feature::thread_tmp_18_fu_342_p2() {
    tmp_18_fu_342_p2 = (!tmp_17_fu_336_p2.read().is_01() || !padding.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_17_fu_336_p2.read()) - sc_biguint<32>(padding.read()));
}

void load_feature::thread_tmp_19_fu_410_p0() {
    tmp_19_fu_410_p0 = hin.read();
}

void load_feature::thread_tmp_19_fu_410_p1() {
    tmp_19_fu_410_p1 =  (sc_lv<31>) (tmp_19_fu_410_p10.read());
}

void load_feature::thread_tmp_19_fu_410_p10() {
    tmp_19_fu_410_p10 = esl_zext<32,31>(c_reg_200.read());
}

void load_feature::thread_tmp_19_fu_410_p2() {
    tmp_19_fu_410_p2 = (!tmp_19_fu_410_p0.read().is_01() || !tmp_19_fu_410_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(tmp_19_fu_410_p0.read()) * sc_biguint<31>(tmp_19_fu_410_p1.read());
}

void load_feature::thread_tmp_20_fu_280_p1() {
    tmp_20_fu_280_p1 = kx.read().range(31-1, 0);
}

void load_feature::thread_tmp_21_fu_438_p1() {
    tmp_21_fu_438_p1 = hin.read();
}

void load_feature::thread_tmp_21_fu_438_p2() {
    tmp_21_fu_438_p2 = (!yi_fu_419_p2.read().is_01() || !tmp_21_fu_438_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(yi_fu_419_p2.read()) < sc_bigint<32>(tmp_21_fu_438_p1.read()));
}

void load_feature::thread_tmp_22_fu_459_p2() {
    tmp_22_fu_459_p2 = (!j_cast_fu_455_p1.read().is_01() || !kx.read().is_01())? sc_lv<1>(): (sc_bigint<32>(j_cast_fu_455_p1.read()) < sc_bigint<32>(kx.read()));
}

void load_feature::thread_tmp_22_mid1_fu_519_p0() {
    tmp_22_mid1_fu_519_p0 =  (sc_lv<31>) (tmp_22_mid1_fu_519_p00.read());
}

void load_feature::thread_tmp_22_mid1_fu_519_p00() {
    tmp_22_mid1_fu_519_p00 = esl_zext<32,31>(c_s_fu_475_p2.read());
}

void load_feature::thread_tmp_22_mid1_fu_519_p1() {
    tmp_22_mid1_fu_519_p1 = hin.read();
}

void load_feature::thread_tmp_22_mid1_fu_519_p2() {
    tmp_22_mid1_fu_519_p2 = (!tmp_22_mid1_fu_519_p0.read().is_01() || !tmp_22_mid1_fu_519_p1.read().is_01())? sc_lv<32>(): sc_biguint<31>(tmp_22_mid1_fu_519_p0.read()) * sc_bigint<32>(tmp_22_mid1_fu_519_p1.read());
}

void load_feature::thread_tmp_22_mid2_fu_524_p3() {
    tmp_22_mid2_fu_524_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<32>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? tmp_22_mid1_fu_519_p2.read(): tmp_19_fu_410_p2.read());
}

void load_feature::thread_tmp_24_dup_fu_589_p2() {
    tmp_24_dup_fu_589_p2 = (!smax_cast_reg_826.read().is_01() || !index_1_mid_fu_495_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(smax_cast_reg_826.read()) + sc_biguint<32>(index_1_mid_fu_495_p3.read()));
}

void load_feature::thread_tmp_24_fu_302_p1() {
    tmp_24_fu_302_p1 = ky.read().range(31-1, 0);
}

void load_feature::thread_tmp_25_fu_710_p1() {
    tmp_25_fu_710_p1 = win.read();
}

void load_feature::thread_tmp_25_fu_710_p2() {
    tmp_25_fu_710_p2 = (!xi_fu_691_p2.read().is_01() || !tmp_25_fu_710_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(xi_fu_691_p2.read()) < sc_bigint<32>(tmp_25_fu_710_p1.read()));
}

void load_feature::thread_tmp_26_fu_727_p2() {
    tmp_26_fu_727_p2 = (!tmp5_mid2_fu_644_p2.read().is_01() || !xi_fu_691_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp5_mid2_fu_644_p2.read()) + sc_biguint<32>(xi_fu_691_p2.read()));
}

void load_feature::thread_tmp_26_mid1_fu_625_p1() {
    tmp_26_mid1_fu_625_p1 = hin.read();
}

void load_feature::thread_tmp_26_mid1_fu_625_p2() {
    tmp_26_mid1_fu_625_p2 = (!yi_mid1_fu_606_p2.read().is_01() || !tmp_26_mid1_fu_625_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(yi_mid1_fu_606_p2.read()) < sc_bigint<32>(tmp_26_mid1_fu_625_p1.read()));
}

void load_feature::thread_tmp_26_mid_fu_390_p1() {
    tmp_26_mid_fu_390_p1 = hin.read();
}

void load_feature::thread_tmp_26_mid_fu_390_p2() {
    tmp_26_mid_fu_390_p2 = (!tmp_18_fu_342_p2.read().is_01() || !tmp_26_mid_fu_390_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_18_fu_342_p2.read()) < sc_bigint<32>(tmp_26_mid_fu_390_p1.read()));
}

void load_feature::thread_tmp_27_cast_fu_733_p1() {
    tmp_27_cast_fu_733_p1 = esl_sext<33,32>(tmp_26_fu_727_p2.read());
}

void load_feature::thread_tmp_27_fu_376_p3() {
    tmp_27_fu_376_p3 = tmp_18_fu_342_p2.read().range(31, 31);
}

void load_feature::thread_tmp_27_mid_fu_560_p3() {
    tmp_27_mid_fu_560_p3 = (!exitcond_flatten_fu_490_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_490_p2.read()[0].to_bool())? tmp_s_reg_821.read(): tmp_22_fu_459_p2.read());
}

void load_feature::thread_tmp_28_fu_798_p1() {
    tmp_28_fu_798_p1 = esl_sext<64,32>(index_2_mid2_reg_887_pp0_iter8_reg.read());
}

void load_feature::thread_tmp_29_fu_794_p1() {
    tmp_29_fu_794_p1 = esl_sext<64,32>(index_2_mid2_reg_887_pp0_iter8_reg.read());
}

void load_feature::thread_tmp_30_fu_752_p2() {
    tmp_30_fu_752_p2 = (!index_2_mid2_fu_598_p3.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(index_2_mid2_fu_598_p3.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void load_feature::thread_tmp_31_fu_424_p3() {
    tmp_31_fu_424_p3 = yi_fu_419_p2.read().range(31, 31);
}

void load_feature::thread_tmp_32_fu_611_p3() {
    tmp_32_fu_611_p3 = yi_mid1_fu_606_p2.read().range(31, 31);
}

void load_feature::thread_tmp_33_fu_696_p3() {
    tmp_33_fu_696_p3 = xi_fu_691_p2.read().range(31, 31);
}

void load_feature::thread_tmp_fu_443_p2() {
    tmp_fu_443_p2 = (!tmp_19_fu_410_p2.read().is_01() || !yi_fu_419_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_19_fu_410_p2.read()) + sc_biguint<32>(yi_fu_419_p2.read()));
}

void load_feature::thread_tmp_mid1_fu_630_p2() {
    tmp_mid1_fu_630_p2 = (!yi_mid1_fu_606_p2.read().is_01() || !tmp_22_mid2_fu_524_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(yi_mid1_fu_606_p2.read()) + sc_biguint<32>(tmp_22_mid2_fu_524_p3.read()));
}

void load_feature::thread_tmp_mid_fu_532_p2() {
    tmp_mid_fu_532_p2 = (!tmp_18_reg_841.read().is_01() || !tmp_22_mid1_fu_519_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_18_reg_841.read()) + sc_biguint<32>(tmp_22_mid1_fu_519_p2.read()));
}

void load_feature::thread_tmp_s_fu_274_p2() {
    tmp_s_fu_274_p2 = (!kx.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(kx.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void load_feature::thread_xi_fu_691_p2() {
    xi_fu_691_p2 = (!j_cast_mid2_cast_fu_671_p1.read().is_01() || !tmp_16_reg_836.read().is_01())? sc_lv<32>(): (sc_biguint<32>(j_cast_mid2_cast_fu_671_p1.read()) + sc_biguint<32>(tmp_16_reg_836.read()));
}

void load_feature::thread_yi_fu_419_p2() {
    yi_fu_419_p2 = (!tmp_18_reg_841.read().is_01() || !i_cast_mid1_fu_415_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_18_reg_841.read()) + sc_biguint<32>(i_cast_mid1_fu_415_p1.read()));
}

void load_feature::thread_yi_mid1_fu_606_p2() {
    yi_mid1_fu_606_p2 = (!i_cast_fu_594_p1.read().is_01() || !tmp_18_reg_841.read().is_01())? sc_lv<32>(): (sc_biguint<32>(i_cast_fu_594_p1.read()) + sc_biguint<32>(tmp_18_reg_841.read()));
}

void load_feature::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter8.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten2_fu_464_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter8.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten2_fu_464_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

}

